bandienthoai/Entities/SanPham.cs
namespace bandienthoai.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web;

    [Table("SanPham")]
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
            ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int MaSP { get; set; }

        [StringLength(255)]
        [DisplayName("Tên sản phẩm")]
        [Required(ErrorMessage = "Chưa nhập tên sản phẩm")]
        public string TenSP { get; set; }

        [StringLength(255)]
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "Chưa nhập mô tả")]
        [DataType(DataType.MultilineText)]
        public string MoTa { get; set; }

        public int SLTon { get; set; }

        [DisplayName("Mã nhà sản xuất")]
        public int MaNSX { get; set; }

        public int SoLanMua { get; set; }

        [StringLength(255)]
        public string HinhAnh { get; set; }

        [DisplayName("Mã nhà cung cấp")]
        public int MaNCC { get; set; }

        [DisplayName("Đơn giá")]
        [Required(ErrorMessage = "Chưa nhập đơn giá")]
        public int DonGia { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }

        public virtual NhaCungCap NhaCungCap { get; set; }

        public virtual NhaSanXuat NhaSanXuat { get; set; }

        [NotMapped]
        [DisplayName("Hình ảnh")]
        [Required(ErrorMessage = "Chưa chọn hình ảnh")]
        public HttpPostedFileBase UploadHinhAnh { get; set; }
    }
}

bandienthoai/Controllers/GioHangController.cs
using bandienthoai.DAO;
using bandienthoai.Entities;
using bandienthoai.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bandienthoai.Controllers
{
    public class GioHangController : BaseController
    {
        public BanDienThoaiContext db = new BanDienThoaiContext();

        // GET: GioHang
        public ActionResult Index()
        {
            NguoiDungDAO ndDAO = new NguoiDungDAO();
            GioHangDAO ghDAO = new GioHangDAO();

            NguoiDung nd = ndDAO.getByTaiKhoan(Session["TAIKHOAN"].ToString());
            Session["GIOHANG"] = ghDAO.getGioHangByND(nd.MaNguoiDung);

            int tongDDH = ghDAO.getTongSPByND(nd.MaNguoiDung);
            int tongGTDDH = ghDAO.getTongGTDDHByND(nd.MaNguoiDung);
            Session.Add("DDH", tongDDH);
            Session.Add("GIATRIDDH", tongGTDDH);

            return View((List<GioHangModel>) Session["GIOHANG"]);

        }

        public ActionResult ChinhSua(int idDDH, int idCT)
        {
            var ghDAO = new GioHangDAO();
            return View(ghDAO.getItemGH(idCT, idDDH));
        }

        [HttpPost]
        public ActionResult ChinhSua(GioHangModel model)
        {
            GioHangDAO ghDAO = new GioHangDAO();
            ghDAO.updateGH(model.MaCHTDDH, model.SoLuong);

            return RedirectToAction("Index");
        }

        public ActionResult DeleteItemGH(int idSP, int idDDH)
        {
            GioHangDAO ghDAO = new GioHangDAO();
            NguoiDungDAO ndDAO = new NguoiDungDAO();
            NguoiDung nd = ndDAO.getByTaiKhoan(Session["TAIKHOAN"].ToString());
            ghDAO.deleteGH(idSP, idDDH, (List<GioHangModel>) Session["GIOHANG"]);

            return RedirectToAction("Index");
        }

        public ActionResult AddSP(int idSP)
        {
            List<GioHangModel> gh = (List<GioHangModel>)Session["GIOHANG"];
            NguoiDungDAO ndDAO = new NguoiDungDAO();
            var ghDAO = new GioHangDAO();
            NguoiDung nd = ndDAO.getByTaiKhoan(Session["TAIKHOAN"].ToString());
            Session["GIOHANG"] = ghDAO.addGH(nd.MaNguoiDung, idSP, gh);

            return RedirectToAction("Index");
        }

        public ActionResult ThanhToan()
        {
            var listGH = (List<GioHangModel>)Session["GIOHANG"];
            ViewBag.GioHang = listGH;
            DonDatHang ddh = db.DonDatHangs.Find(listGH[0].MaDDH);

            return View(ddh);
        }

        [HttpPost]
        public ActionResult ThanhToan(DonDatHang ddh)
        {
            var listGH = (List<GioHangModel>)Session["GIOHANG"];
            var item = db.DonDatHangs.Find(ddh.MaDDH);
            item.DiaChiGiao = ddh.DiaChiGiao;
            item.MaTrangThai = 1;
            item.NgayDat = DateTime.Now;
            db.SaveChanges();


            //chua fix dk
            //foreach(var a in listGH)
            //{
            //    SanPham sp = db.SanPhams.Find(a.MaSP);
            //    sp.SLTon -= a.SoLuong;
            //    sp.SoLanMua += a.SoLuong;

            //    db.SaveChanges();
            //}

            

            return RedirectToAction("Index");
        }
    }
}

bandienthoai/Controllers/SanPhamController.cs
using bandienthoai.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bandienthoai.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        public ActionResult ChiTiet(int id)
        {
            var spDAO = new SanPhamDAO();
            return View(spDAO.GetSPById(id));
        }

        public PartialViewResult Single_Product_Related()
        {
            var spDAO = new SanPhamDAO();
            return PartialView("Single_Product_Related", spDAO.GetAllSP());
        }
    }
}

bandienthoai/Views/SanPham/ChiTiet.cshtml
@model bandienthoai.Entities.SanPham
@{
    ViewBag.Title = "ChiTiet";
    Layout = "~/Views/Shared/MyLayout2.cshtml";
    string dongia = Model.DonGia + "$";
    string urlImg = "~/Assets/Admin/img/imgSP/" + Model.HinhAnh;
}

<div class="single-product-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            @Html.Partial("Single_Product_Left")

            <div class="col-md-8">
                <div class="product-content-right">

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="product-images">
                                <div class="product-main-img">
                                    <img src="@Url.Content(urlImg)" alt="">
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="product-inner">
                                <h2 class="product-name">@Model.TenSP</h2>
                                <div class="product-inner-price">
                                    <ins>@dongia</ins>
                                </div>

                                <a href="@Url.Action("AddSP", "GioHang", new { idSP = Model.MaSP })" class="add-to-cart-link"><i class="fa fa-shopping-cart"></i>Thêm giỏ hàng</a> 

                                <div role="tabpanel">
                                    <ul class="product-tab" role="tablist">
                                        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Description</a></li>
                                    </ul>
                                    <div class="tab-content">
                                        <div role="tabpanel" class="tab-pane fade in active" id="home">
                                            <h2>Product Description</h2>
                                            <p>@Model.MoTa</p>
                                        </div>
                                        
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>


                   @{Html.RenderAction("Single_Product_Related");}
                </div>
            </div>
        </div>
    </div>
</div>

bandienthoai/Views/SanPham/Single_Product_Related.cshtml
@model IEnumerable<bandienthoai.Entities.SanPham>

    <div class="related-products-wrapper">
        <h2 class="related-products-title">Sản phẩm tương tự</h2>
        <div class="related-products-carousel">
            @foreach (var a in Model)
            {
                string urlImg = "~/Assets/Admin/img/imgSP/" + a.HinhAnh;
                string dongia = a.DonGia + "$";

                <div class="single-product">
                    <div class="product-f-image">
                        <img src="@Url.Content(urlImg)" alt="">
                        <div class="product-hover">
                            <a href="@Url.Action("AddSP", "GioHang", new { idSP = a.MaSP })" class="add-to-cart-link"><i class="fa fa-shopping-cart"></i>Thêm giỏ hàng</a>
                            <a href="@Url.Action("ChiTiet", "SanPham", new { id = a.MaSP })" class="view-details-link"><i class="fa fa-link"></i>Chi tiết</a>
                        </div>
                    </div>

                    <h2><a href="">@a.TenSP</a></h2>

                    <div class="product-carousel-price">
                        <ins>@dongia</ins>
                    </div>
                </div>
            }

           
        </div>
    </div>