bandienthoai/Areas/Admin/Controllers/AdminProfileController.cs
using bandienthoai.DAO;
using bandienthoai.Entities;
using bandienthoai.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace bandienthoai.Areas.Admin.Controllers
{
    public class AdminProfileController : Controller
    {
        private BanDienThoaiContext db = new BanDienThoaiContext();

        public ActionResult ProfileById(int id)
        {
            var ndDAO = new NguoiDungDAO();
            var nguoidung = ndDAO.getById(id);
            return View(nguoidung);
        }

        //GET list Profile
        public ActionResult AllProfile()
        {
            var ndDAO = new NguoiDungDAO();
            return View(ndDAO.getAllAdmin());
        }
        // GET: Admin/AdminProfile
        public ActionResult Profile()
        {
            var ndDAO = new NguoiDungDAO();
            var nguoidung = ndDAO.getByTaiKhoan(Session["TAIKHOAN"].ToString());
            return View(nguoidung);
        }

        //Dang xuat
        public ActionResult Logout()
        {
            Session["TAIKHOAN"] = null;
            Session["HINHANH"] = null;
            Session.Clear();

            return RedirectToAction("Login", "NguoiDung", new { area = ""});
        }

        //tao tai khoan
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(SignupModel model)
        {
            var ndDAO = new NguoiDungDAO();
            if (ModelState.IsValid)
            {
                if (ndDAO.checkData(model))
                {
                    ndDAO.InsertAdmin(model);
                    return RedirectToAction("AllProfile");
                }
                else
                    ModelState.AddModelError("", "Đăng ký không thành công, tài khoản hoặc số điện thoại đã tồn tại");

            }

            return View(model);
        }

        //chinh sua
        public ActionResult Edit()
        {
            var ndDAO = new NguoiDungDAO();
            var nguoiDung = ndDAO.getByTaiKhoan(Session["TAIKHOAN"].ToString());
            return View(nguoiDung);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NguoiDung nguoiDung)
        {
            if (ModelState.IsValid)
            {
                var ndDAO = new NguoiDungDAO();
                

                var nd = db.NguoiDungs.Find(nguoiDung.MaNguoiDung);

                if (nguoiDung.UploadHinhAnh != null)
                {
                    string fileName = Path.GetFileName(nguoiDung.UploadHinhAnh.FileName);
                    string filePath = "~/Assets/Admin/img/" + fileName;
                    nguoiDung.UploadHinhAnh.SaveAs(Server.MapPath(filePath));

                    nd.HinhAnh = fileName;
                }

                ndDAO.Edit(nguoiDung);
                db.SaveChanges();

                return RedirectToAction("Profile");
            }
            return View(nguoiDung);
        }



        
    }
}

bandienthoai/Areas/Admin/Controllers/LoginController.cs
using bandienthoai.DAO;
using bandienthoai.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bandienthoai.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        // GET: Admin/Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var ndDAO = new NguoiDungDAO();
                var result = ndDAO.Login(model.taikhoan, model.matkhau);
                if (result)
                {
                    var taikhoan = model.taikhoan;
                    Session.Add("TAIKHOAN", taikhoan);
                    return RedirectToAction("Index", "test");
                }
                else
                {
                    ModelState.AddModelError("", "Đăng nhập không thành công.");
                }
            }
            return View("Index");
        }

    }
}

bandienthoai/Areas/Admin/Views/AdminProfile/AllProfile.cshtml
@model IEnumerable<bandienthoai.Entities.NguoiDung>
@{
    ViewBag.Title = "AllProfile";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Danh sách người dùng</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Tài khoản</th>
                            <th>Họ tên</th>
                            <th>Địa chỉ</th>
                            <th>Số điện thoại</th>
                            <th>Email</th>
                            <th>Giới tính</th>
                            <th>Ngày sinh</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var a in Model)
                        {
                            string ngaysinh = a.NgaySinh.ToString("dd/MM/yyyy");
                            <tr>
                                <td>@a.TaiKhoan</td>
                                <td>@a.HoTen</td>
                                <td>@a.DiaChi</td>
                                <td>@a.SDT</td>
                                <td>@a.Email</td>
                                <td>@a.GioiTinh</td>
                                <td>@ngaysinh</td>
                                <td>@Html.ActionLink("Chi tiết", "ProfileById", new { id = a.MaNguoiDung })</td>
                            </tr>
                        }


                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-header py-3">
            @Html.ActionLink("Tạo mới", "Create")
        </div>
    </div>

bandienthoai/Areas/Admin/Views/AdminProfile/Create.cshtml
@model bandienthoai.Models.SignupModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

@using (Html.BeginForm())
{

    <div class="signup-container">
        <h1>Đăng ký</h1>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen)
            @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { placeholder = "Nhập họ tên", @class = "input-signup" } })
            @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaiKhoan)
            @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { placeholder = "Nhập tài khoản", @class = "input-signup" } })
            @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT)
            @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { placeholder = "Nhập số điện thoại", @class = "input-signup" } })
            @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi)
            @Html.EditorFor(model => model.DiaChi, new { @class = "input-signup", htmlAttributes = new { placeholder = "Nhập địa chỉ", @class = "input-signup" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email)
            @Html.EditorFor(model => model.Email, new { @class = "input-signup", htmlAttributes = new { placeholder = "Nhập email", @class = "input-signup" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau)
            @Html.EditorFor(model => model.MatKhau, new { @class = "input-signup", htmlAttributes = new { placeholder = "Nhập mật khẩu", @class = "input-signup" } })
            @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.XacNhanMK)
            @Html.EditorFor(model => model.XacNhanMK, new { htmlAttributes = new { placeholder = "Xác nhận mật khẩu", @class = "input-signup" } })
            @Html.ValidationMessageFor(model => model.XacNhanMK, "", new { @class = "text-danger" })
        </div>

        <div class="form-group birth-of-date">
            @Html.LabelFor(model => model.NgaySinh)
            @Html.EditorFor(model => model.NgaySinh, "{0:dd/MM/yyyy}", new { @class = "input-signup", htmlAttributes = new { placeholder = "Nhập ngày sinh" } })
            @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh)
            @Html.RadioButtonFor(model => model.GioiTinh, "nam") @Html.Label("Nam")
            @Html.RadioButtonFor(model => model.GioiTinh, "nữ") @Html.Label("Nữ")
            @Html.RadioButtonFor(model => model.GioiTinh, "khác") @Html.Label("Giới tính khác")
            @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
        </div>


        <button type="submit" class="signupbtn">Đăng ký</button>

    </div>
}

<style>
    .signup-container {
        width: 980px;
        margin: auto;
        margin: 10px auto;
        padding: 10px;
        border: 1px solid #ccc;
        overflow: hidden;
        position: relative;
    }

        .signup-container h1 {
            margin-bottom: 25px;
        }

    .input-signup {
        width: 100%;
        padding: 15px;
        /*margin: 5px 0 22px 0;*/
        display: inline-block;
        border: none;
        background: #f1f1f1;
    }

        .input-signup:focus {
            background-color: #ddd;
            outline: none;
        }

    .birth-of-date {
        margin-bottom: 20px;
    }
    /* Set a style for all buttons */
    .signupbtn {
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 20px auto;
        border: none;
        cursor: pointer;
        width: 100%;
        opacity: 0.9;
        width: 50%;
        display: table;
    }

        .signupbtn:hover {
            opacity: 1;
        }
</style>

bandienthoai/Areas/Admin/Views/AdminProfile/Edit.cshtml
@model bandienthoai.Entities.NguoiDung
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
    string urlImg = "~/Assets/Admin/img/" + Model.HinhAnh;
    string ngaysinh = Model.NgaySinh.ToString("dd/MM/yyyy");
}

@using (Html.BeginForm("Edit", "AdminProfile", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Chỉnh sửa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNguoiDung)

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaiKhoan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, "{0:dd/MM/yyyy}", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh)
            @Html.RadioButtonFor(model => model.GioiTinh, "nam") @Html.Label("Nam")
            @Html.RadioButtonFor(model => model.GioiTinh, "nữ") @Html.Label("Nữ")
            @Html.RadioButtonFor(model => model.GioiTinh, "khác") @Html.Label("Giới tính khác")
            @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
        </div>

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.UploadHinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <img src="@Url.Content(urlImg)" style="margin:10px; border:2px solid #676565; border-radius:100px" height="200" width="200" id="imagePreview" />
                    <input type="file" name="UploadHinhAnh" accept="image/jpeg, image/png, image/jpg" onchange="ShowImagePreview(this, document.getElementById('imagePreview'))" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script>
    function ShowImagePreview(imageUploader, previewImage) {
        if (imageUploader.files && imageUploader.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $(previewImage).attr('src', e.target.result);
            }
            reader.readAsDataURL(imageUploader.files[0]);
        }
    }

</script>

bandienthoai/Areas/Admin/Views/AdminProfile/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h2>Login</h2>

bandienthoai/Areas/Admin/Views/AdminProfile/Profile.cshtml
@model bandienthoai.Entities.NguoiDung
@{
    ViewBag.Title = "Profile";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
    string urlImg = "~/Assets/Admin/img/" + Model.HinhAnh;
    var ngaysinh = Model.NgaySinh.ToString("dd/MM/yyyy");
}

<div class="account-infor-container">
    <div class="imageUser">
        <img src="@Url.Content(urlImg)" height="200" width="200" style="border:2px solid #676565; border-radius:80px" />
    </div>

    <div>

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.LoaiNguoiDung.TenLoaiND)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LoaiNguoiDung.TenLoaiND)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HoTen)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HoTen)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TaiKhoan)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TaiKhoan)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.DiaChi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DiaChi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SDT)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SDT)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GioiTinh)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GioiTinh)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NgaySinh)
            </dt>

            <dd>
                @ngaysinh
            </dd>

        </dl>
    </div>




</div>

bandienthoai/Areas/Admin/Views/AdminProfile/ProfileById.cshtml
@model bandienthoai.Entities.NguoiDung
@{
    ViewBag.Title = "ProfileById";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
    string urlImg = "~/Assets/Admin/img/" + Model.HinhAnh;
    var ngaysinh = Model.NgaySinh.ToString("dd/MM/yyyy");
}

<div class="account-infor-container">
    <div class="imageUser">
        <img src="@Url.Content(urlImg)" height="200" width="200" style="border:2px solid #676565; border-radius:80px" />
    </div>

    <div>

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.LoaiNguoiDung.TenLoaiND)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LoaiNguoiDung.TenLoaiND)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HoTen)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HoTen)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TaiKhoan)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TaiKhoan)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.DiaChi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DiaChi)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SDT)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SDT)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GioiTinh)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GioiTinh)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NgaySinh)
            </dt>

            <dd>
                @ngaysinh
            </dd>

        </dl>
    </div>




</div>